#include <arpa/inet.h>
#include <cerrno>
#include <cstdarg>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <netinet/in.h>
#include <sys/socket.h>
#include <unistd.h>

#ifndef UDP_TELEMETRY_ENABLE_ACK
#define UDP_TELEMETRY_ENABLE_ACK 1
#endif

namespace {

constexpr std::uint16_t kDefaultPort = 5002;

// Keep every status line flushed into the QVM log. The target verify script
// depends on the stable "udp-telemetry-server:" prefix.
void logf(const char *fmt, ...)
{
    va_list args;
    va_start(args, fmt);
    std::vprintf(fmt, args);
    va_end(args);
    std::fflush(stdout);
}

int open_listener(std::uint16_t port)
{
    // Bind a plain IPv4 UDP listener inside Guest B. The direct virtio-net link
    // supplies the network path; no host-side vdevpeer interface is involved.
    int fd = socket(AF_INET, SOCK_DGRAM, 0);
    if (fd == -1) {
        logf("udp-telemetry-server: socket failed: %s\n", std::strerror(errno));
        return -1;
    }

    int reuse = 1;
    setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &reuse, sizeof(reuse));

    sockaddr_in addr{};
    addr.sin_family = AF_INET;
    addr.sin_addr.s_addr = htonl(INADDR_ANY);
    addr.sin_port = htons(port);

    if (bind(fd, reinterpret_cast<sockaddr *>(&addr), sizeof(addr)) == -1) {
        logf("udp-telemetry-server: bind port=%u failed: %s\n",
             static_cast<unsigned>(port), std::strerror(errno));
        close(fd);
        return -1;
    }

    logf("udp-telemetry-server: listening address=0.0.0.0 port=%u ack=%s\n",
         static_cast<unsigned>(port), UDP_TELEMETRY_ENABLE_ACK ? "on" : "off");
    return fd;
}

const char *peer_ip_string(const sockaddr_in &peer, char *buf, std::size_t size)
{
    const char *converted = inet_ntop(AF_INET, &peer.sin_addr, buf, size);
    return converted != nullptr ? converted : "unknown";
}

std::uint32_t extract_sequence(const char *payload)
{
    // Payloads generated by Guest A begin with "seq=N". If the datagram is from
    // another source or malformed, ACK sequence 0 makes that visible in logs.
    const char *seq = std::strstr(payload, "seq=");
    if (seq == nullptr) {
        return 0;
    }
    return static_cast<std::uint32_t>(std::strtoul(seq + 4, nullptr, 10));
}

void send_ack(int fd, const sockaddr_in &peer, socklen_t peer_len, std::uint32_t seq)
{
#if UDP_TELEMETRY_ENABLE_ACK
    char ack[64];
    const int len = std::snprintf(ack, sizeof(ack), "ack seq=%u\n", seq);
    if (len <= 0 || static_cast<std::size_t>(len) >= sizeof(ack)) {
        logf("udp-telemetry-server: ack format failed seq=%u\n", seq);
        return;
    }

    const ssize_t sent = sendto(fd, ack, static_cast<std::size_t>(len), 0,
                                reinterpret_cast<const sockaddr *>(&peer), peer_len);
    if (sent == -1) {
        logf("udp-telemetry-server: ack send failed seq=%u: %s\n",
             seq, std::strerror(errno));
        return;
    }
    logf("udp-telemetry-server: ack sent seq=%u\n", seq);
#else
    (void)fd;
    (void)peer;
    (void)peer_len;
    (void)seq;
#endif
}

} // namespace

int main(int argc, char **argv)
{
    std::uint16_t port = kDefaultPort;
    if (argc > 1) {
        unsigned long parsed = std::strtoul(argv[1], nullptr, 0);
        if (parsed > 0 && parsed <= 65535) {
            port = static_cast<std::uint16_t>(parsed);
        }
    }

    const int fd = open_listener(port);
    if (fd == -1) {
        return 1;
    }

    for (;;) {
        sockaddr_in peer{};
        socklen_t peer_len = sizeof(peer);
        char payload[512];

        // UDP delivers one complete datagram per successful recvfrom() call,
        // preserving message boundaries without TCP-style line reassembly.
        const ssize_t received = recvfrom(fd, payload, sizeof(payload) - 1, 0,
                                          reinterpret_cast<sockaddr *>(&peer), &peer_len);
        if (received == -1) {
            if (errno == EINTR) {
                continue;
            }
            logf("udp-telemetry-server: recvfrom failed: %s\n", std::strerror(errno));
            continue;
        }

        payload[received] = '\0';
        char peer_ip[INET_ADDRSTRLEN] = {};
        const std::uint32_t seq = extract_sequence(payload);
        logf("udp-telemetry-server: received peer=%s:%u %s",
             peer_ip_string(peer, peer_ip, sizeof(peer_ip)),
             static_cast<unsigned>(ntohs(peer.sin_port)), payload);
        send_ack(fd, peer, peer_len, seq);
    }
}
